'use client';

import { motion } from 'framer-motion';
import { ArrowLeft, ShieldAlert } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb';
import { useAuditStore } from '@/lib/store';

const sectionVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.08, duration: 0.45, ease: 'easeOut' },
  }),
};

const sections = [
  {
    id: 'information-we-collect',
    title: '1. Information We Collect',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          When you use LinkHygiene, we may collect the following types of information:
        </p>
        <ul className="ml-5 list-disc space-y-2 text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          <li>
            <strong className="text-gray-800 dark:text-gray-200">URLs you submit for analysis</strong> — We temporarily store the website URLs you enter for the purpose of performing SEO and link audits. These URLs are not shared with third parties for marketing purposes.
          </li>
          <li>
            <strong className="text-gray-800 dark:text-gray-200">Audit results and analysis data</strong> — The findings generated by our AI-powered analysis tool, including link health data, SEO scores, and recommendations, are stored to provide you with audit history.
          </li>
          <li>
            <strong className="text-gray-800 dark:text-gray-200">Usage data</strong> — We collect anonymized data about how you interact with our service, including pages visited, features used, and session duration, to improve our platform.
          </li>
          <li>
            <strong className="text-gray-800 dark:text-gray-200">Device and browser information</strong> — We automatically collect certain information about your device, including browser type, operating system, and screen resolution.
          </li>
        </ul>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          We do <strong className="text-gray-800 dark:text-gray-200">not</strong> require account registration, and we do not collect personal identifying information such as names, email addresses, or phone numbers unless you voluntarily provide them through our contact form.
        </p>
      </div>
    ),
  },
  {
    id: 'how-we-use-information',
    title: '2. How We Use Information',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          The information we collect is used for the following purposes:
        </p>
        <ul className="ml-5 list-disc space-y-2 text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          <li>To perform AI-powered SEO and link hygiene audits on websites you submit.</li>
          <li>To provide, maintain, and improve the LinkHygiene service and user experience.</li>
          <li>To store audit history and allow you to compare previous scans.</li>
          <li>To analyze usage patterns and optimize our platform's performance.</li>
          <li>To respond to your inquiries and provide customer support.</li>
          <li>To detect and prevent technical issues, abuse, or security threats.</li>
        </ul>
      </div>
    ),
  },
  {
    id: 'data-storage-security',
    title: '3. Data Storage & Security',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          We take reasonable measures to protect the information we collect. Your data is stored using industry-standard encryption and security protocols. However, no method of transmission over the Internet or electronic storage is 100% secure.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          Audit data is retained for a limited period to provide you with audit history functionality. You may request deletion of your audit data at any time by contacting us.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          We do not sell, trade, or otherwise transfer your personal information to outside parties except as required to provide our service or as mandated by law.
        </p>
      </div>
    ),
  },
  {
    id: 'third-party-services',
    title: '4. Third-Party Services',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          LinkHygiene may integrate with or rely on third-party services for:
        </p>
        <ul className="ml-5 list-disc space-y-2 text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          <li>AI model providers for generating audit analysis and recommendations.</li>
          <li>Analytics services to understand usage patterns.</li>
          <li>Content delivery networks (CDNs) for optimal performance.</li>
          <li>Advertising networks to support our free service model.</li>
        </ul>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          These third-party services may have their own privacy policies, and we encourage you to review them. We are not responsible for the privacy practices of third-party services.
        </p>
      </div>
    ),
  },
  {
    id: 'cookies-tracking',
    title: '5. Cookies & Tracking',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          LinkHygiene uses cookies and similar tracking technologies to enhance your experience. Cookies are small data files stored on your device that help us remember your preferences, understand usage patterns, and deliver relevant content.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          We use the following types of cookies:
        </p>
        <ul className="ml-5 list-disc space-y-2 text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          <li><strong className="text-gray-800 dark:text-gray-200">Essential cookies</strong> — Required for the basic functionality of our service.</li>
          <li><strong className="text-gray-800 dark:text-gray-200">Analytics cookies</strong> — Help us understand how visitors interact with our service.</li>
          <li><strong className="text-gray-800 dark:text-gray-200">Advertising cookies</strong> — Used to deliver relevant advertisements and measure ad effectiveness.</li>
        </ul>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          For more details, please refer to our{' '}
          <button
            onClick={() => useAuditStore.getState().setPage('cookies')}
            className="text-cyan-600 underline hover:text-cyan-500 dark:text-cyan-400 dark:hover:text-cyan-300"
          >
            Cookie Policy
          </button>.
        </p>
      </div>
    ),
  },
  {
    id: 'your-rights',
    title: '6. Your Rights',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          Depending on your jurisdiction, you may have the following rights regarding your data:
        </p>
        <ul className="ml-5 list-disc space-y-2 text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          <li><strong className="text-gray-800 dark:text-gray-200">Right to access</strong> — Request a copy of the data we hold about you.</li>
          <li><strong className="text-gray-800 dark:text-gray-200">Right to rectification</strong> — Request correction of inaccurate data.</li>
          <li><strong className="text-gray-800 dark:text-gray-200">Right to deletion</strong> — Request deletion of your audit data and personal information.</li>
          <li><strong className="text-gray-800 dark:text-gray-200">Right to restrict processing</strong> — Request that we limit how we use your data.</li>
          <li><strong className="text-gray-800 dark:text-gray-200">Right to data portability</strong> — Request your data in a structured, machine-readable format.</li>
          <li><strong className="text-gray-800 dark:text-gray-200">Right to object</strong> — Object to the processing of your data for specific purposes.</li>
        </ul>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          To exercise any of these rights, please contact us using the information provided below.
        </p>
      </div>
    ),
  },
  {
    id: 'changes-to-policy',
    title: '7. Changes to This Policy',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          We may update this Privacy Policy from time to time to reflect changes in our practices, technology, or legal requirements. When we make changes, we will update the &quot;Last Updated&quot; date at the top of this page.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          We encourage you to review this policy periodically. Your continued use of LinkHygiene after any changes constitutes your acceptance of the updated policy.
        </p>
      </div>
    ),
  },
  {
    id: 'contact',
    title: '8. Contact',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:
        </p>
        <div className="rounded-lg border border-cyan-100 bg-cyan-50/50 p-4 dark:border-cyan-900/50 dark:bg-cyan-950/20">
          <p className="text-sm font-medium text-gray-800 dark:text-gray-200">LinkHygiene Privacy Team</p>
          <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">Email: privacy@linkhygiene.com</p>
          <p className="text-sm text-gray-600 dark:text-gray-400">
            You can also reach us through our{' '}
            <button
              onClick={() => useAuditStore.getState().setPage('contact')}
              className="text-cyan-600 underline hover:text-cyan-500 dark:text-cyan-400 dark:hover:text-cyan-300"
            >
              Contact page
            </button>.
          </p>
        </div>
      </div>
    ),
  },
];

export function PrivacyPolicyPage() {
  const setPage = useAuditStore((s) => s.setPage);

  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      <main className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Breadcrumb */}
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.35 }}
        >
          <Breadcrumb>
            <BreadcrumbList>
              <BreadcrumbItem>
                <BreadcrumbLink
                  asChild
                  className="cursor-pointer text-sm text-cyan-600 hover:text-cyan-500 dark:text-cyan-400 dark:hover:text-cyan-300"
                >
                  <button onClick={() => setPage('home')}>Home</button>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage className="text-sm font-medium text-gray-800 dark:text-gray-200">
                  Privacy Policy
                </BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
        </motion.div>

        {/* Back Button */}
        <motion.div
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.35, delay: 0.05 }}
          className="mt-4"
        >
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setPage('home')}
            className="gap-2 text-gray-600 hover:text-cyan-600 dark:text-gray-400 dark:hover:text-cyan-400"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Button>
        </motion.div>

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, delay: 0.1 }}
          className="mt-6 mb-8"
        >
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
            Last updated: January 2025
          </p>
          <div className="mt-1 h-1 w-20 rounded-full bg-gradient-to-r from-cyan-600 to-teal-500" />
        </motion.div>

        {/* AI Disclaimer — Prominent */}
        <motion.div
          initial={{ opacity: 0, scale: 0.97 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.45, delay: 0.15 }}
        >
          <Card className="border-amber-200 bg-amber-50/60 dark:border-amber-800/60 dark:bg-amber-950/20">
            <CardContent className="p-4 sm:p-5">
              <div className="flex items-start gap-3">
                <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-amber-100 dark:bg-amber-900/40">
                  <ShieldAlert className="h-4.5 w-4.5 text-amber-600 dark:text-amber-400" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-sm font-semibold text-amber-800 dark:text-amber-300">
                    Important AI Disclaimer
                  </h3>
                  <ul className="space-y-1.5 text-sm text-amber-700 dark:text-amber-400/90">
                    <li className="flex gap-2">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-amber-500 dark:bg-amber-400" />
                      <span>
                        LinkHygiene is an AI-powered tool. The analysis provided is generated by artificial intelligence and should not be considered professional advice.
                      </span>
                    </li>
                    <li className="flex gap-2">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-amber-500 dark:bg-amber-400" />
                      <span>
                        We do not take responsibility for any decisions made based on AI-generated audit results.
                      </span>
                    </li>
                    <li className="flex gap-2">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-amber-500 dark:bg-amber-400" />
                      <span>
                        AI analysis may produce incomplete, inaccurate, or outdated information.
                      </span>
                    </li>
                    <li className="flex gap-2">
                      <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-amber-500 dark:bg-amber-400" />
                      <span>
                        Users are responsible for independently verifying all audit findings before taking action.
                      </span>
                    </li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Introduction */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.45, delay: 0.2 }}
          className="mt-8 text-sm leading-relaxed text-gray-600 dark:text-gray-400"
        >
          At LinkHygiene, we are committed to protecting your privacy and ensuring transparency about how we handle your information. This Privacy Policy describes the types of information we collect, how we use it, and the measures we take to safeguard your data when you use our AI-powered SEO and link audit service.
        </motion.p>

        {/* Sections */}
        {sections.map((section, i) => (
          <motion.section
            key={section.id}
            custom={i}
            initial="hidden"
            animate="visible"
            variants={sectionVariants}
            className="mt-8"
            aria-labelledby={section.id}
          >
            <Card className="overflow-hidden">
              <CardHeader className="border-b border-gray-100 bg-gray-50/50 py-4 dark:border-gray-800 dark:bg-gray-900/30">
                <CardTitle
                  id={section.id}
                  className="text-base font-semibold text-gray-900 dark:text-white"
                >
                  {section.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="py-5">{section.content}</CardContent>
            </Card>
          </motion.section>
        ))}

        {/* Footer note */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: sections.length * 0.08 + 0.2, duration: 0.45 }}
          className="mt-10 border-t border-gray-200 pt-6 text-center dark:border-gray-800"
        >
          <p className="text-xs text-gray-400 dark:text-gray-500">
            &copy; {new Date().getFullYear()} LinkHygiene. All rights reserved.
          </p>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setPage('home')}
            className="mt-3 gap-1.5 text-xs text-gray-500 hover:text-cyan-600 dark:text-gray-400 dark:hover:text-cyan-400"
          >
            <ArrowLeft className="h-3 w-3" />
            Back to Home
          </Button>
        </motion.div>
      </main>
    </div>
  );
}