'use client';

import { motion } from 'framer-motion';
import { ArrowLeft, TriangleAlert } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb';
import { useAuditStore } from '@/lib/store';

const sectionVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.08, duration: 0.45, ease: 'easeOut' },
  }),
};

const sections = [
  {
    id: 'acceptance-of-terms',
    title: '1. Acceptance of Terms',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          By accessing or using LinkHygiene (&quot;the Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you must not use the Service.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          These Terms constitute a legally binding agreement between you (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) and LinkHygiene. We reserve the right to update or modify these Terms at any time without prior notice. Your continued use of the Service following any changes constitutes acceptance of those changes.
        </p>
      </div>
    ),
  },
  {
    id: 'description-of-service',
    title: '2. Description of Service',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          LinkHygiene is a free, web-based tool that performs automated SEO audits and link hygiene analysis on websites. The Service analyzes submitted URLs to identify broken links, SEO issues, meta-tag problems, and provides AI-generated insights and recommendations.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          The Service is provided &quot;as is&quot; and is intended for informational and educational purposes only. Features and functionality may be added, removed, or modified at any time at our sole discretion.
        </p>
      </div>
    ),
  },
  {
    id: 'user-responsibilities',
    title: '3. User Responsibilities',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          By using LinkHygiene, you agree to:
        </p>
        <ul className="ml-5 list-disc space-y-2 text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          <li>Only submit URLs that you have the right to analyze or that are publicly accessible.</li>
          <li>Not use the Service for any unlawful, harmful, or abusive purpose.</li>
          <li>Not attempt to disrupt, overload, or interfere with the Service&apos;s infrastructure.</li>
          <li>Not use automated scripts, bots, or scraping tools to access the Service beyond normal usage.</li>
          <li>Not reproduce, redistribute, or resell any part of the Service or its output without prior written consent.</li>
          <li>Independently verify all audit findings before taking any action based on the results.</li>
          <li>Understand that the Service uses AI technology and its results may contain errors.</li>
        </ul>
      </div>
    ),
  },
  {
    id: 'intellectual-property',
    title: '4. Intellectual Property',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          All content, design, graphics, and software associated with LinkHygiene are the property of LinkHygiene or its licensors and are protected by applicable intellectual property laws. This includes, but is not limited to, the LinkHygiene name, logo, website design, and underlying code.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          You may not copy, modify, distribute, or create derivative works from any part of the Service without our express written permission. Audit reports generated by the Service are provided for your personal, non-commercial use.
        </p>
      </div>
    ),
  },
  {
    id: 'modifications',
    title: '5. Modifications & Discontinuation',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          LinkHygiene reserves the right to modify, suspend, or discontinue the Service (or any part thereof) at any time, with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          We also reserve the right to update these Terms at any time. Material changes will be reflected by updating the &quot;Effective Date&quot; at the top of this page. Continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.
        </p>
      </div>
    ),
  },
  {
    id: 'governing-law',
    title: '6. Governing Law',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in the applicable jurisdiction.
        </p>
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.
        </p>
      </div>
    ),
  },
  {
    id: 'contact',
    title: '7. Contact',
    content: (
      <div className="space-y-3">
        <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
          If you have any questions or concerns about these Terms, please contact us:
        </p>
        <div className="rounded-lg border border-cyan-100 bg-cyan-50/50 p-4 dark:border-cyan-900/50 dark:bg-cyan-950/20">
          <p className="text-sm font-medium text-gray-800 dark:text-gray-200">LinkHygiene Legal Team</p>
          <p className="mt-1 text-sm text-gray-600 dark:text-gray-400">Email: legal@linkhygiene.com</p>
          <p className="text-sm text-gray-600 dark:text-gray-400">
            You can also reach us through our{' '}
            <button
              onClick={() => useAuditStore.getState().setPage('contact')}
              className="text-cyan-600 underline hover:text-cyan-500 dark:text-cyan-400 dark:hover:text-cyan-300"
            >
              Contact page
            </button>.
          </p>
        </div>
      </div>
    ),
  },
];

export function TermsPage() {
  const setPage = useAuditStore((s) => s.setPage);

  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      <main className="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Breadcrumb */}
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.35 }}
        >
          <Breadcrumb>
            <BreadcrumbList>
              <BreadcrumbItem>
                <BreadcrumbLink
                  asChild
                  className="cursor-pointer text-sm text-cyan-600 hover:text-cyan-500 dark:text-cyan-400 dark:hover:text-cyan-300"
                >
                  <button onClick={() => setPage('home')}>Home</button>
                </BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage className="text-sm font-medium text-gray-800 dark:text-gray-200">
                  Terms of Service
                </BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
        </motion.div>

        {/* Back Button */}
        <motion.div
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.35, delay: 0.05 }}
          className="mt-4"
        >
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setPage('home')}
            className="gap-2 text-gray-600 hover:text-cyan-600 dark:text-gray-400 dark:hover:text-cyan-400"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Button>
        </motion.div>

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, delay: 0.1 }}
          className="mt-6 mb-8"
        >
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-white sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
            Effective date: January 2025
          </p>
          <div className="mt-1 h-1 w-20 rounded-full bg-gradient-to-r from-cyan-600 to-teal-500" />
        </motion.div>

        {/* AI Disclaimer — Very Prominent */}
        <motion.div
          initial={{ opacity: 0, scale: 0.97 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.45, delay: 0.15 }}
        >
          <Card className="border-red-200 bg-red-50/60 dark:border-red-800/60 dark:bg-red-950/20">
            <CardContent className="p-4 sm:p-5">
              <div className="flex items-start gap-3">
                <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-red-100 dark:bg-red-900/40">
                  <TriangleAlert className="h-4.5 w-4.5 text-red-600 dark:text-red-400" />
                </div>
                <div className="space-y-3">
                  <h3 className="text-sm font-bold text-red-800 dark:text-red-300">
                    Critical AI Disclaimer — Please Read Carefully
                  </h3>
                  <div className="space-y-2.5 text-sm text-red-700 dark:text-red-400/90">
                    <div className="rounded-md border border-red-200/60 bg-white/60 p-3 dark:border-red-800/40 dark:bg-red-950/30">
                      <p className="font-semibold uppercase tracking-wide">
                        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND.
                      </p>
                    </div>
                    <ul className="space-y-2">
                      <li className="flex gap-2">
                        <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-red-500 dark:bg-red-400" />
                        <span>
                          LinkHygiene utilizes artificial intelligence technology for website analysis. AI-generated results may contain errors, omissions, or inaccuracies.
                        </span>
                      </li>
                      <li className="flex gap-2">
                        <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-red-500 dark:bg-red-400" />
                        <span className="font-medium">
                          WE DO NOT TAKE RESPONSIBILITY FOR ANY LOSSES, DAMAGES, OR CONSEQUENCES ARISING FROM THE USE OF AI-GENERATED AUDIT RESULTS.
                        </span>
                      </li>
                      <li className="flex gap-2">
                        <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-red-500 dark:bg-red-400" />
                        <span>
                          Users acknowledge that AI analysis is not a substitute for professional SEO consultation.
                        </span>
                      </li>
                      <li className="flex gap-2">
                        <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-red-500 dark:bg-red-400" />
                        <span>
                          The tool should be used for informational purposes only.
                        </span>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Limitation of Liability — also prominent */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, delay: 0.2 }}
          className="mt-6"
        >
          <Card className="border-orange-200 bg-orange-50/50 dark:border-orange-800/50 dark:bg-orange-950/15">
            <CardHeader className="border-b border-orange-200/50 py-3 dark:border-orange-800/30">
              <CardTitle className="text-base font-semibold text-orange-800 dark:text-orange-300">
                Limitation of Liability
              </CardTitle>
            </CardHeader>
            <CardContent className="py-4">
              <div className="space-y-3 text-sm text-orange-700 dark:text-orange-400/90">
                <p>
                  To the fullest extent permitted by applicable law, LinkHygiene and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from:
                </p>
                <ul className="ml-5 list-disc space-y-1.5">
                  <li>Your use of or inability to use the Service.</li>
                  <li>Any AI-generated analysis, recommendations, or audit results.</li>
                  <li>Unauthorized access, use, or alteration of your transmissions or content.</li>
                  <li>Any other matter relating to the Service.</li>
                </ul>
                <p>
                  In no event shall our total liability to you for all claims arising from or related to the Service exceed the amount you have paid to us (which is zero, as the Service is free).
                </p>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Introduction */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.45, delay: 0.25 }}
          className="mt-8 text-sm leading-relaxed text-gray-600 dark:text-gray-400"
        >
          Welcome to LinkHygiene. These Terms of Service govern your use of our AI-powered SEO and link audit platform. Please read them carefully before using the Service.
        </motion.p>

        {/* Sections */}
        {sections.map((section, i) => (
          <motion.section
            key={section.id}
            custom={i}
            initial="hidden"
            animate="visible"
            variants={sectionVariants}
            className="mt-8"
            aria-labelledby={section.id}
          >
            <Card className="overflow-hidden">
              <CardHeader className="border-b border-gray-100 bg-gray-50/50 py-4 dark:border-gray-800 dark:bg-gray-900/30">
                <CardTitle
                  id={section.id}
                  className="text-base font-semibold text-gray-900 dark:text-white"
                >
                  {section.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="py-5">{section.content}</CardContent>
            </Card>
          </motion.section>
        ))}

        {/* Footer note */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: sections.length * 0.08 + 0.3, duration: 0.45 }}
          className="mt-10 border-t border-gray-200 pt-6 text-center dark:border-gray-800"
        >
          <p className="text-xs text-gray-400 dark:text-gray-500">
            &copy; {new Date().getFullYear()} LinkHygiene. All rights reserved.
          </p>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setPage('home')}
            className="mt-3 gap-1.5 text-xs text-gray-500 hover:text-cyan-600 dark:text-gray-400 dark:hover:text-cyan-400"
          >
            <ArrowLeft className="h-3 w-3" />
            Back to Home
          </Button>
        </motion.div>
      </main>
    </div>
  );
}